plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

def packageJson = new groovy.json.JsonSlurper().parse(file('../package.json'))
def playServicesAuthVersion = rootProject.ext.has('playServicesAuthVersion')
  ? rootProject.ext.get('playServicesAuthVersion')
  : '21.5.1'

group = 'expo.modules.phonenumberhint'
version = packageJson.version

android {
  namespace "expo.modules.phonenumberhint"
  defaultConfig {
    versionCode 1
    versionName packageJson.version
    consumerProguardFiles("proguard-rules.pro")
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  implementation "com.google.android.gms:play-services-auth:$playServicesAuthVersion"
}
